-- Hakuryū Dashboard
-- Migração de ficha RPG centralizada, permissões granulares, banimentos,
-- cargos atribuíveis e tipos de treino.
-- Execute no SQL Editor do Supabase depois do schema base/migracao_multigang.sql.

-- Ficha única por jogador, compartilhada por todas as gangs.
CREATE TABLE IF NOT EXISTS public.perfis_jogador (
  discord_id TEXT PRIMARY KEY,
  discord_username TEXT,
  nome_roblox TEXT,
  nome_rp TEXT,
  genero TEXT,
  altura_jogo NUMERIC,
  estilo_luta_principal TEXT,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.perfis_jogador ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.perfis_jogador TO authenticated;
GRANT ALL ON public.perfis_jogador TO service_role;

-- Permissões granulares dos cargos personalizados.
CREATE TABLE IF NOT EXISTS public.cargos_painel_personalizados (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gang_id BIGINT NOT NULL REFERENCES public.gangs(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  discord_role_id TEXT NOT NULL,
  permissoes TEXT[] NOT NULL DEFAULT '{}',
  cargos_atribuiveis TEXT[] NOT NULL DEFAULT '{}',
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT cargos_painel_personalizados_gang_role_key UNIQUE (gang_id, discord_role_id)
);

ALTER TABLE public.cargos_painel_personalizados
  ADD COLUMN IF NOT EXISTS cargos_atribuiveis TEXT[] NOT NULL DEFAULT '{}';

UPDATE public.cargos_painel_personalizados
SET cargos_atribuiveis = '{}'::TEXT[]
WHERE cargos_atribuiveis IS NULL;

ALTER TABLE public.cargos_painel_personalizados ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.cargos_painel_personalizados TO authenticated;
GRANT ALL ON public.cargos_painel_personalizados TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated, service_role;

-- Configuração por gang dos alertas de inatividade.
CREATE TABLE IF NOT EXISTS public.config_inatividade (
  gang_id BIGINT PRIMARY KEY REFERENCES public.gangs(id) ON DELETE CASCADE,
  dias_limite INTEGER NOT NULL DEFAULT 30 CHECK (dias_limite BETWEEN 7 AND 365),
  percentual_minimo INTEGER NOT NULL DEFAULT 50 CHECK (percentual_minimo BETWEEN 0 AND 100),
  alerta_ativo BOOLEAN NOT NULL DEFAULT true,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.config_inatividade ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.config_inatividade TO authenticated;
GRANT ALL ON public.config_inatividade TO service_role;

-- Índices que aceleram a verificação de banimento e a sincronização da ficha.
CREATE INDEX IF NOT EXISTS membros_gang_status_idx
  ON public.membros (gang_id, status);
CREATE INDEX IF NOT EXISTS membros_discord_id_idx
  ON public.membros (discord_id);
CREATE INDEX IF NOT EXISTS punicoes_membro_tipo_gang_idx
  ON public.punicoes (gang_id, membro_id, tipo);

-- Tipos de treino ficam em texto para permitir múltiplas tags. O campo legado
-- `tipo` continua como marcador de classificação para compatibilidade.
ALTER TABLE public.treinos
  ADD COLUMN IF NOT EXISTS tipos TEXT[];

-- Instalações antigas possuem treinos_tipo_check, que só aceitava Interno,
-- Amistoso, Obrigatório e Extra. As tags agora são validadas pela aplicação.
ALTER TABLE public.treinos DROP CONSTRAINT IF EXISTS treinos_tipo_check;

UPDATE public.treinos
SET tipos = CASE
  WHEN tipo IS NULL OR btrim(tipo) = '' THEN ARRAY['Gladiador']::TEXT[]
  WHEN tipo = ANY (ARRAY['Interno', 'Obrigatório']) THEN ARRAY['Gladiador']::TEXT[]
  ELSE ARRAY[tipo]::TEXT[]
END
WHERE tipos IS NULL;

-- O campo legado continua preenchido com a primeira tag para compatibilidade
-- com integrações antigas; a aplicação passa a ler/escrever `tipos`.
NOTIFY pgrst, 'reload schema';
